on:
  push:
    branches: [master]

name: 🚀 Deploy CI4 Application

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Sync  files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude="public/" --exclude=".env"
          path: .
          remote_path: /home/batuahcoba/domains/ujicoba.batuah.tech/arima-bpjs
          remote_host: ujicoba.batuah.tech
          remote_user: batuahcoba
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Sync public files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude=".env" --exclude="index.php" --exclude="cgi-bin/" --exclude="assets/"
          path: public/
          remote_path: /home/batuahcoba/domains/ujicoba.batuah.tech/public_html/
          remote_host: ujicoba.batuah.tech
          remote_user: batuahcoba
          remote_key: ${{ secrets.DEPLOY_KEY }}
